"""add models UserMax column username

Revision ID: 04bab362afc4
Revises: 4786c0ed0f2d
Create Date: 2026-04-28 08:49:57.569919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04bab362afc4'
down_revision: Union[str, Sequence[str], None] = '4786c0ed0f2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_max', sa.Column('username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_max', 'username')
    # ### end Alembic commands ###
