"""delete UserMax imege

Revision ID: 4786c0ed0f2d
Revises: c7a2c8c086b4
Create Date: 2026-04-28 08:41:07.114809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4786c0ed0f2d'
down_revision: Union[str, Sequence[str], None] = 'c7a2c8c086b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'image_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('image_data', postgresql.BYTEA(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
